var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.createTemplateTagFirstArg=function(a){return a.raw=a};$jscomp.createTemplateTagFirstArgWithRaw=function(a,b){a.raw=b;return a};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};
$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};
$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,b){var c=$jscomp.propertyToPolyfillSymbol[b];if(null==c)return a[b];c=a[c];return void 0!==c?c:a[b]};$jscomp.polyfill=function(a,b,c,f){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,c,f):$jscomp.polyfillUnisolated(a,b,c,f))};
$jscomp.polyfillUnisolated=function(a,b,c,f){c=$jscomp.global;a=a.split(".");for(f=0;f<a.length-1;f++){var d=a[f];if(!(d in c))return;c=c[d]}a=a[a.length-1];f=c[a];b=b(f);b!=f&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,c,f){var d=a.split(".");a=1===d.length;f=d[0];f=!a&&f in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var g=0;g<d.length-1;g++){var e=d[g];if(!(e in f))return;f=f[e]}d=d[d.length-1];c=$jscomp.IS_SYMBOL_NATIVE&&"es6"===c?f[d]:null;b=b(c);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,d,{configurable:!0,writable:!0,value:b}):b!==c&&(void 0===$jscomp.propertyToPolyfillSymbol[d]&&(c=1E9*Math.random()>>>0,$jscomp.propertyToPolyfillSymbol[d]=$jscomp.IS_SYMBOL_NATIVE?
$jscomp.global.Symbol(d):$jscomp.POLYFILL_PREFIX+c+"$"+d),$jscomp.defineProperty(f,$jscomp.propertyToPolyfillSymbol[d],{configurable:!0,writable:!0,value:b})))};$jscomp.underscoreProtoCanBeSet=function(){var a={a:!0},b={};try{return b.__proto__=a,b.a}catch(c){}return!1};
$jscomp.setPrototypeOf=$jscomp.TRUST_ES6_POLYFILLS&&"function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null;$jscomp.generator={};$jscomp.generator.ensureIteratorResultIsObject_=function(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");};
$jscomp.generator.Context=function(){this.isRunning_=!1;this.yieldAllIterator_=null;this.yieldResult=void 0;this.nextAddress=1;this.finallyAddress_=this.catchAddress_=0;this.finallyContexts_=this.abruptCompletion_=null};$jscomp.generator.Context.prototype.start_=function(){if(this.isRunning_)throw new TypeError("Generator is already running");this.isRunning_=!0};$jscomp.generator.Context.prototype.stop_=function(){this.isRunning_=!1};
$jscomp.generator.Context.prototype.jumpToErrorHandler_=function(){this.nextAddress=this.catchAddress_||this.finallyAddress_};$jscomp.generator.Context.prototype.next_=function(a){this.yieldResult=a};$jscomp.generator.Context.prototype.throw_=function(a){this.abruptCompletion_={exception:a,isException:!0};this.jumpToErrorHandler_()};$jscomp.generator.Context.prototype.return=function(a){this.abruptCompletion_={return:a};this.nextAddress=this.finallyAddress_};
$jscomp.generator.Context.prototype.jumpThroughFinallyBlocks=function(a){this.abruptCompletion_={jumpTo:a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.yield=function(a,b){this.nextAddress=b;return{value:a}};$jscomp.generator.Context.prototype.yieldAll=function(a,b){a=$jscomp.makeIterator(a);var c=a.next();$jscomp.generator.ensureIteratorResultIsObject_(c);if(c.done)this.yieldResult=c.value,this.nextAddress=b;else return this.yieldAllIterator_=a,this.yield(c.value,b)};
$jscomp.generator.Context.prototype.jumpTo=function(a){this.nextAddress=a};$jscomp.generator.Context.prototype.jumpToEnd=function(){this.nextAddress=0};$jscomp.generator.Context.prototype.setCatchFinallyBlocks=function(a,b){this.catchAddress_=a;void 0!=b&&(this.finallyAddress_=b)};$jscomp.generator.Context.prototype.setFinallyBlock=function(a){this.catchAddress_=0;this.finallyAddress_=a||0};$jscomp.generator.Context.prototype.leaveTryBlock=function(a,b){this.nextAddress=a;this.catchAddress_=b||0};
$jscomp.generator.Context.prototype.enterCatchBlock=function(a){this.catchAddress_=a||0;a=this.abruptCompletion_.exception;this.abruptCompletion_=null;return a};$jscomp.generator.Context.prototype.enterFinallyBlock=function(a,b,c){c?this.finallyContexts_[c]=this.abruptCompletion_:this.finallyContexts_=[this.abruptCompletion_];this.catchAddress_=a||0;this.finallyAddress_=b||0};
$jscomp.generator.Context.prototype.leaveFinallyBlock=function(a,b){b=this.finallyContexts_.splice(b||0)[0];if(b=this.abruptCompletion_=this.abruptCompletion_||b){if(b.isException)return this.jumpToErrorHandler_();void 0!=b.jumpTo&&this.finallyAddress_<b.jumpTo?(this.nextAddress=b.jumpTo,this.abruptCompletion_=null):this.nextAddress=this.finallyAddress_}else this.nextAddress=a};$jscomp.generator.Context.prototype.forIn=function(a){return new $jscomp.generator.Context.PropertyIterator(a)};
$jscomp.generator.Context.PropertyIterator=function(a){this.object_=a;this.properties_=[];for(var b in a)this.properties_.push(b);this.properties_.reverse()};$jscomp.generator.Context.PropertyIterator.prototype.getNext=function(){for(;0<this.properties_.length;){var a=this.properties_.pop();if(a in this.object_)return a}return null};$jscomp.generator.Engine_=function(a){this.context_=new $jscomp.generator.Context;this.program_=a};
$jscomp.generator.Engine_.prototype.next_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_.next,a,this.context_.next_);this.context_.next_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.return_=function(a){this.context_.start_();var b=this.context_.yieldAllIterator_;if(b)return this.yieldAllStep_("return"in b?b["return"]:function(c){return{value:c,done:!0}},a,this.context_.return);this.context_.return(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.throw_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_["throw"],a,this.context_.next_);this.context_.throw_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.yieldAllStep_=function(a,b,c){try{var f=a.call(this.context_.yieldAllIterator_,b);$jscomp.generator.ensureIteratorResultIsObject_(f);if(!f.done)return this.context_.stop_(),f;var d=f.value}catch(g){return this.context_.yieldAllIterator_=null,this.context_.throw_(g),this.nextStep_()}this.context_.yieldAllIterator_=null;c.call(this.context_,d);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.nextStep_=function(){for(;this.context_.nextAddress;)try{var a=this.program_(this.context_);if(a)return this.context_.stop_(),{value:a.value,done:!1}}catch(b){this.context_.yieldResult=void 0,this.context_.throw_(b)}this.context_.stop_();if(this.context_.abruptCompletion_){a=this.context_.abruptCompletion_;this.context_.abruptCompletion_=null;if(a.isException)throw a.exception;return{value:a.return,done:!0}}return{value:void 0,done:!0}};
$jscomp.generator.Generator_=function(a){this.next=function(b){return a.next_(b)};this.throw=function(b){return a.throw_(b)};this.return=function(b){return a.return_(b)};this[Symbol.iterator]=function(){return this}};$jscomp.generator.createGenerator=function(a,b){b=new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(b));$jscomp.setPrototypeOf&&a.prototype&&$jscomp.setPrototypeOf(b,a.prototype);return b};
$jscomp.asyncExecutePromiseGenerator=function(a){function b(f){return a.next(f)}function c(f){return a.throw(f)}return new Promise(function(f,d){function g(e){e.done?f(e.value):Promise.resolve(e.value).then(b,c).then(g,d)}g(a.next())})};$jscomp.asyncExecutePromiseGeneratorFunction=function(a){return $jscomp.asyncExecutePromiseGenerator(a())};$jscomp.asyncExecutePromiseGeneratorProgram=function(a){return $jscomp.asyncExecutePromiseGenerator(new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(a)))};
$jscomp.initSymbol=function(){};$jscomp.polyfill("Symbol",function(a){if(a)return a;var b=function(g,e){this.$jscomp$symbol$id_=g;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:e})};b.prototype.toString=function(){return this.$jscomp$symbol$id_};var c="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",f=0,d=function(g){if(this instanceof d)throw new TypeError("Symbol is not a constructor");return new b(c+(g||"")+"_"+f++,g)};return d},"es6","es3");
$jscomp.polyfill("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var f=$jscomp.global[b[c]];"function"===typeof f&&"function"!=typeof f.prototype[a]&&$jscomp.defineProperty(f.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}})}return a},"es6",
"es3");$jscomp.iteratorPrototype=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a};
$jscomp.polyfill("Promise",function(a){function b(){this.batch_=null}function c(e){return e instanceof d?e:new d(function(h,k){h(e)})}if(a&&(!($jscomp.FORCE_POLYFILL_PROMISE||$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION&&"undefined"===typeof $jscomp.global.PromiseRejectionEvent)||!$jscomp.global.Promise||-1===$jscomp.global.Promise.toString().indexOf("[native code]")))return a;b.prototype.asyncExecute=function(e){if(null==this.batch_){this.batch_=[];var h=this;this.asyncExecuteFunction(function(){h.executeBatch_()})}this.batch_.push(e)};
var f=$jscomp.global.setTimeout;b.prototype.asyncExecuteFunction=function(e){f(e,0)};b.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var e=this.batch_;this.batch_=[];for(var h=0;h<e.length;++h){var k=e[h];e[h]=null;try{k()}catch(l){this.asyncThrow_(l)}}}this.batch_=null};b.prototype.asyncThrow_=function(e){this.asyncExecuteFunction(function(){throw e;})};var d=function(e){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];this.isRejectionHandled_=!1;var h=this.createResolveAndReject_();
try{e(h.resolve,h.reject)}catch(k){h.reject(k)}};d.prototype.createResolveAndReject_=function(){function e(l){return function(m){k||(k=!0,l.call(h,m))}}var h=this,k=!1;return{resolve:e(this.resolveTo_),reject:e(this.reject_)}};d.prototype.resolveTo_=function(e){if(e===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(e instanceof d)this.settleSameAsPromise_(e);else{a:switch(typeof e){case "object":var h=null!=e;break a;case "function":h=!0;break a;default:h=!1}h?this.resolveToNonPromiseObj_(e):
this.fulfill_(e)}};d.prototype.resolveToNonPromiseObj_=function(e){var h=void 0;try{h=e.then}catch(k){this.reject_(k);return}"function"==typeof h?this.settleSameAsThenable_(h,e):this.fulfill_(e)};d.prototype.reject_=function(e){this.settle_(2,e)};d.prototype.fulfill_=function(e){this.settle_(1,e)};d.prototype.settle_=function(e,h){if(0!=this.state_)throw Error("Cannot settle("+e+", "+h+"): Promise already settled in state"+this.state_);this.state_=e;this.result_=h;2===this.state_&&this.scheduleUnhandledRejectionCheck_();
this.executeOnSettledCallbacks_()};d.prototype.scheduleUnhandledRejectionCheck_=function(){var e=this;f(function(){if(e.notifyUnhandledRejection_()){var h=$jscomp.global.console;"undefined"!==typeof h&&h.error(e.result_)}},1)};d.prototype.notifyUnhandledRejection_=function(){if(this.isRejectionHandled_)return!1;var e=$jscomp.global.CustomEvent,h=$jscomp.global.Event,k=$jscomp.global.dispatchEvent;if("undefined"===typeof k)return!0;"function"===typeof e?e=new e("unhandledrejection",{cancelable:!0}):
"function"===typeof h?e=new h("unhandledrejection",{cancelable:!0}):(e=$jscomp.global.document.createEvent("CustomEvent"),e.initCustomEvent("unhandledrejection",!1,!0,e));e.promise=this;e.reason=this.result_;return k(e)};d.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var e=0;e<this.onSettledCallbacks_.length;++e)g.asyncExecute(this.onSettledCallbacks_[e]);this.onSettledCallbacks_=null}};var g=new b;d.prototype.settleSameAsPromise_=function(e){var h=this.createResolveAndReject_();
e.callWhenSettled_(h.resolve,h.reject)};d.prototype.settleSameAsThenable_=function(e,h){var k=this.createResolveAndReject_();try{e.call(h,k.resolve,k.reject)}catch(l){k.reject(l)}};d.prototype.then=function(e,h){function k(n,p){return"function"==typeof n?function(r){try{l(n(r))}catch(t){m(t)}}:p}var l,m,q=new d(function(n,p){l=n;m=p});this.callWhenSettled_(k(e,l),k(h,m));return q};d.prototype.catch=function(e){return this.then(void 0,e)};d.prototype.callWhenSettled_=function(e,h){function k(){switch(l.state_){case 1:e(l.result_);
break;case 2:h(l.result_);break;default:throw Error("Unexpected state: "+l.state_);}}var l=this;null==this.onSettledCallbacks_?g.asyncExecute(k):this.onSettledCallbacks_.push(k);this.isRejectionHandled_=!0};d.resolve=c;d.reject=function(e){return new d(function(h,k){k(e)})};d.race=function(e){return new d(function(h,k){for(var l=$jscomp.makeIterator(e),m=l.next();!m.done;m=l.next())c(m.value).callWhenSettled_(h,k)})};d.all=function(e){var h=$jscomp.makeIterator(e),k=h.next();return k.done?c([]):new d(function(l,
m){function q(r){return function(t){n[r]=t;p--;0==p&&l(n)}}var n=[],p=0;do n.push(void 0),p++,c(k.value).callWhenSettled_(q(n.length-1),m),k=h.next();while(!k.done)})};return d},"es6","es3");
$jscomp.polyfill("String.fromCodePoint",function(a){return a?a:function(b){for(var c="",f=0;f<arguments.length;f++){var d=Number(arguments[f]);if(0>d||1114111<d||d!==Math.floor(d))throw new RangeError("invalid_code_point "+d);65535>=d?c+=String.fromCharCode(d):(d-=65536,c+=String.fromCharCode(d>>>10&1023|55296),c+=String.fromCharCode(d&1023|56320))}return c}},"es6","es3");
$jscomp.iteratorFromArray=function(a,b){a instanceof String&&(a+="");var c=0,f=!1,d={next:function(){if(!f&&c<a.length){var g=c++;return{value:b(g,a[g]),done:!1}}f=!0;return{done:!0,value:void 0}}};d[Symbol.iterator]=function(){return d};return d};$jscomp.polyfill("Array.prototype.values",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(b,c){return c})}},"es8","es3");
$jscomp.checkStringArgs=function(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""};
$jscomp.polyfill("String.prototype.startsWith",function(a){return a?a:function(b,c){var f=$jscomp.checkStringArgs(this,b,"startsWith");b+="";var d=f.length,g=b.length;c=Math.max(0,Math.min(c|0,f.length));for(var e=0;e<g&&c<d;)if(f[c++]!=b[e++])return!1;return e>=g}},"es6","es3");$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(b){return b})}},"es6","es3");
var BLOCKED="@X",SKIP="@S",PREDEFINED_ARRANGEMENTS={patterns:"P\nA A\nT T T\nT T T T\nE E E E E\nR R R R R R\nN N N N N N N\nS S S S S S S S",mathematics:"M\nA A\nT T T\nH H H H\nE E E E E\nM M M M M M\nA A A A A A A\nT T T T T T\nI I I I I\nC C C C\nS S S",triangle:"T\nR R\nI I I\nA A A A\nN N N\nG G\nL L L\nE E E E",pascal:'$pascal ROW\n\nreplace "ROW" above with row number then click Create to generate Pascal\'s triangle up to that row\n',forbidden:"S\n1 1\n1 2 1\n1 3 3 1\n1 4 "+BLOCKED+" 4 "+
BLOCKED+"\n"+BLOCKED+" 5 4 4 4 "+BLOCKED+"\n"+BLOCKED+" 5 9 8 8 "+BLOCKED+" "+BLOCKED,skip:"A\nB B\nC C C\nD "+SKIP+" "+SKIP+" D\nE E E E E\n"+SKIP+" F F "+SKIP+"\nG G "+SKIP+" G G\nH H H H H H",invert:"#$invert\n$pascal 15\ndelete the hashtag and click create to see what happens",mustafa:"M\nU U\nS S S\nT T T T\nA A A A A\nF F F F F F\nA A A A A A A\nM M M M M M M M\nO O O O O O O\nT T T T T T\nI I I I I\nW W W W\nA A A\nL L\nA",javascript:"J\nA A\nV V V\nA A A A\nS S S S S\nC C C C C\nR R R R\nI I I\nP P\nT",
mrkwan:"M\nR R\n. . .\nC C C C\nH H H\nI I\nT\nA A\nT T T\nK K K K\nW W W\nA A\nN",punctuation:".\n\\ \\\n< < <\n<< << << <<\n$ $ $ $ $\n>> >> >> >>\n> > >\n/ /\n.",datamgmt:"D D D D\nA A A\nT T\nA\nM M\nA A A\nN N N N\nA A A A A\nG G G G G G\nE E E E E\nM M M M\nE E E\nN N\nT",emoji:[[9729],[128330,128330],[128140,128140,128140],[128139,128139,128139,128139],[127851,127851,127851],[128059,128059,128059],[127810,127810,127810,127810],[127803,127803,127803,127803,127803],[127855,127855,127855,127855],
[128157,128157],[127800,127800,127800],[128152,128152,128152,128152],[128142,128142,128142,128142,128142],[127758,127758,127758,127758],[128032,128032,128032,128032,128032],[127811,127811,127811,127811,127811,127811],[129361,129361,129361,129361,129361],[128012,128012,128012,128012],[129344,129344],[127873,127873,127873],[128081,128081],[127853]].map(function(a){return a.map(function(b){return String.fromCodePoint(b)}).join(" ")}).join("\n"),custom:""},COLORS=[[214,179,243,255],[249,202,72,255],[148,
210,145,255],[65,223,208,255]],COLORIDX=0,CURRENT_ARRANGEMENT=[],NUMPATHS=0,PATHS_READY=!1,PATHS_COMPUTING=!1,TOO_MANY_PATHS=!1,ANIMATION_INTERVAL_ID=-1,_TRI_ADDER_IDS=[],_ADDING_ARR_INPUT=!1,_ADDING_TRIANGLE=!1,_PASCAL_ARRANGEMENT=[];function _on_anim_button_mouseleave(){var a=document.getElementById("anim_button");a.innerHTML=-1===ANIMATION_INTERVAL_ID?"Animate":"Stop Animating";a.disabled=!1;a.style.opacity="100%";a.style.width=110}
function toggle_animate(){if(PATHS_READY)if(-1===ANIMATION_INTERVAL_ID){var a=get_animspeed();ANIMATION_INTERVAL_ID=setInterval(draw_next_path,a);document.getElementById("anim_button").innerHTML="Stop Animating"}else clearInterval(ANIMATION_INTERVAL_ID),ANIMATION_INTERVAL_ID=-1,document.getElementById("anim_button").innerHTML="Animate"}
function toggle_arrangement(){var a=document.getElementById("arr_button"),b=document.getElementById("arr_container"),c=!!b.hidden;b.hidden=!c;a.innerHTML=c?"Hide":"Edit Arrangement"}function choose_random_arrangement(){var a=document.getElementById("arr_input"),b=_.values(PREDEFINED_ARRANGEMENTS).filter(function(f){return f!==a.value&&""!==f}),c=parseInt(Math.random()*b.length);set_arrangement(b[c]);create_arrangement(!0)}
function set_arrangement(a){_ADDING_ARR_INPUT=!1;document.getElementById("arr_input").value=void 0===a?"":a}
function create_arrangement(a,b){_TRI_ADDER_IDS.forEach(function(d){return clearTimeout(d)});_TRI_ADDER_IDS=[];_ADDING_TRIANGLE=!1;b||(document.getElementById("wait_hint").style.visibility="hidden");-1!==ANIMATION_INTERVAL_ID&&toggle_animate();var c=document.getElementById("arr_input").value;CURRENT_ARRANGEMENT=void 0===b?parseInput(c,{doInvert:!1,doCompute:a}):b;var f=document.getElementById("tri_container");(function(){var d,g,e,h,k,l,m;return $jscomp.asyncExecutePromiseGeneratorProgram(function(q){d=
[];g=document.createDocumentFragment();e=0;h=$jscomp.makeIterator(_.range(CURRENT_ARRANGEMENT.length));for(k=h.next();!k.done;k=h.next())l=k.value,m=CURRENT_ARRANGEMENT[l],g.appendChild(create_row(m,l)),e+=m.length,1250<=e&&(d.push(g),g=document.createDocumentFragment(),e=0);d.push(g);return q.return(d)})})().then(function(d){var g=0;f.innerHTML="";_ADDING_TRIANGLE=!0;setTimeout(function h(){g<d.length&&_ADDING_TRIANGLE?(f.appendChild(d[g]),3>g&&center_arrangement(),g++,_TRI_ADDER_IDS.push(setTimeout(h,
100))):(center_arrangement(),on_lookup_input_changed())},0)});b=document.getElementById("pathscount");PATHS_READY=TOO_MANY_PATHS=!1;a&&(b.innerHTML="computing...","computing pascal row"!=CURRENT_ARRANGEMENT[0].slice(0,3).join(" ")&&(PATHS_COMPUTING=!0,computer.postMessage({type:"computePaths",current_arrangement:CURRENT_ARRANGEMENT,blocked:BLOCKED,skip:SKIP,memlimit:get_memlimit(),everynthpath:get_everynthpath(),dotrim:get_dotrim()})))}
function center_arrangement(){var a=document.getElementById("tri_container"),b=a.children;if(0<b.length){var c=_.max(b,function(e){return e.offsetWidth}),f=(a.scrollWidth-c.offsetWidth)/2,d=b.length*b[0].offsetHeight;d=d>a.offsetHeight?0:(a.offsetHeight-d)/2;b=$jscomp.makeIterator(b);for(var g=b.next();!g.done;g=b.next())g=g.value,g.style.left=(c.offsetWidth-g.offsetWidth)/2+f,g.style.top=d;a.scrollLeft=(a.scrollWidth-a.offsetWidth)/2}}
function row_length_differences_are_odd(a){a=$jscomp.makeIterator(_.zip(a,a.slice(1)));for(var b=a.next();!b.done;b=a.next()){var c=$jscomp.makeIterator(b.value);b=c.next().value;c=c.next().value;if(void 0!==c&&1!==Math.abs(c.length-b.length)%2)return!1}return!0}function test_can_animate(){var a=document.getElementById("anim_button");PATHS_READY||(a.style.width="auto",a.style.opacity="50%",a.innerHTML="paths not ready")}
function get_int_value_by_id(a,b,c){a=parseInt(document.getElementById(a).value);return isNaN(a)?b:(null!=c?c:_.identity)(a)}function get_memlimit(){return get_int_value_by_id("m_input",1E9,function(a){return 1E6*a})}function get_everynthpath(){return get_int_value_by_id("nthpath_input",1)}function get_animspeed(){return get_int_value_by_id("anim_speed",500)}function get_dotrim(){return document.getElementById("do_trim_input").checked}
function parseInput(a,b){a=a.trim();var c=a.split("\n");if(a.startsWith("$pascal ")){try{var f=parseInt(a.split(" ").filter(function(d){return""!==d})[1]);if(!isNaN(f))return computer.postMessage({type:"computePascal",row:f,doreverse:b.doInvert,docompute:b.doCompute}),set_arrangement("computing pascal row "+f),parseInput("computing pascal row "+f)}catch(d){console.log("exception in parseInput"),console.log(d)}return parseInput("pascal row")}return"$invert"===c[0].trim()?parseInput(c.slice(1).join("\n"),
_.extend(b,{doInvert:!0})).reverse():c.map(function(d){return d.trim().split(" ").filter(function(g){return""!==g})}).filter(function(d){return 0<d.length})}function get_next_color(){var a=$jscomp.makeIterator(COLORS[COLORIDX]),b=a.next().value,c=a.next().value,f=a.next().value;a=a.next().value;COLORIDX=(COLORIDX+1)%COLORS.length;return"rgba("+b+", "+c+", "+f+", "+a+")"}
function create_row(a,b){var c=document.createElement("div");c.className="row";for(var f=$jscomp.makeIterator(_.range(a.length)),d=f.next();!d.done;d=f.next()){var g=d.value;d=a[g].toString();var e=document.createElement("div");e.className="elem";e.id=b+";"+g;e.cell_value=d;e.numpaths="N/A";d===BLOCKED&&(e.style.backgroundColor="rgb(185, 185, 185)");d===SKIP&&(e.style.backgroundColor="rgb(185, 185, 185)");g=document.createElement("span");g.className="idx";g.innerHTML=e.id;var h=document.createElement("pre");
h.innerHTML=""+d;e.appendChild(g);e.appendChild(h);c.appendChild(e)}return c}function draw_path(a,b,c){a=$jscomp.makeIterator(a);for(var f=a.next();!f.done;f=a.next()){var d=$jscomp.makeIterator(f.value);f=d.next().value;d=d.next().value;f=document.getElementById(f+";"+d);f.cell_value===SKIP?f.style.opacity=""===b?"":"50%":f.style.backgroundColor=c?get_next_color():b}}function draw_next_path(){computer.postMessage({type:"getNextPath"})}
function add_per_block_counts(a){var b=document.getElementById("tri_container");b=$jscomp.makeIterator(b.children);for(var c=b.next();!c.done;c=b.next()){c=$jscomp.makeIterator(c.value.children);for(var f=c.next();!f.done;f=c.next()){f=f.value;var d=_.has(a,f.id)?a[f.id]:0;f.numpaths=d;0===d&&f.cell_value!==BLOCKED&&f.cell_value!==SKIP&&(f.style.backgroundColor="rgb(225, 220, 220)");var g=document.createElement("span");g.className="pbc";g.innerHTML=d;f.appendChild(g)}}}
function add_pascal_arrangement(){function a(f){_ADDING_ARR_INPUT=!0;var d=_.chunk(f.map(function(h){return h.join(" ")}).join("\n"),1E4).map(function(h){return h.join("")}),g=document.getElementById("arr_input");g.value="";var e=0;console.log(d.length);setTimeout(function k(){e<d.length&&_ADDING_ARR_INPUT?(g.value+=d[e++],setTimeout(k,50),0==e%4&&(b.innerHTML="adding"+Array(e%5+1).join("."))):(b.style.visibility="hidden",_PASCAL_ARRANGEMENT=[])},0)}var b=document.getElementById("wait_hint");if(!_ADDING_ARR_INPUT){var c=
_PASCAL_ARRANGEMENT;150<c.length?Swal.fire({title:"Are you sure?",text:"These can get really big and possibly slow down your computer",showDenyButton:!0,showCancelButton:!0,confirmButtonText:"Continue",denyButtonText:"Download (recommended)",cancelButtonText:"Abort"}).then(function(f){f.isDenied||f.isDismissed?f.isDenied&&post_download("pascal"+c.length+".txt"):a(c)}):(b.innerHTML="adding..",a(c))}}
function on_lookup_input_changed(){var a=parseInt(document.getElementById("n_input").value),b=parseInt(document.getElementById("r_input").value),c=document.getElementById("tri_container"),f=document.getElementById("c_output"),d=document.getElementById("p_output");!isNaN(a)&&!isNaN(b)&&0<=a&&a<c.children.length&&0<=b&&b<c.children[a].children.length?(a=c.children[a].children[b],f.innerHTML=a.cell_value,d.innerHTML=a.numpaths):(f.innerHTML="N/A",d.innerHTML="N/A")}
function post_download(a){downloader.postMessage({type:"createDownloadURL",current_arrangement:CURRENT_ARRANGEMENT,suggested:null!=a?a:"arrangement.txt"})}function download_arrangement(a,b){var c=document.createElement("a");c.setAttribute("download",null!=b?b:"arrangement.txt");c.href=a;document.body.appendChild(c);window.requestAnimationFrame(function(){var f=new MouseEvent("click");c.dispatchEvent(f);document.body.removeChild(c)})}
function restart_computer(){computer.terminate();computer=new Worker("/pascal_triangle/pascalesque/computer.js");computer.addEventListener("message",computer_message_f)}
function main(){document.getElementById("anim_button").addEventListener("mouseout",_on_anim_button_mouseleave);document.getElementById("anim_button").addEventListener("mouseover",test_can_animate);document.getElementById("anim_button").addEventListener("click",toggle_animate);document.getElementById("arr_button").addEventListener("click",toggle_arrangement);document.getElementById("create_wpaths").addEventListener("click",function(){return _.wrap(create_arrangement,function(g){restart_computer();
g(!0)})()});document.getElementById("create_wopaths").addEventListener("click",function(){return create_arrangement(!1)});document.getElementById("create_random").addEventListener("click",choose_random_arrangement);document.getElementById("wait_hint").addEventListener("click",add_pascal_arrangement);document.getElementById("download_button").addEventListener("click",function(g){return post_download()});document.getElementById("n_input").addEventListener("input",on_lookup_input_changed);document.getElementById("r_input").addEventListener("input",
on_lookup_input_changed);document.getElementById("anim_speed").addEventListener("input",function(){toggle_animate();toggle_animate()});var a=document.getElementById("pre_options");a.addEventListener("change",function(){set_arrangement(PREDEFINED_ARRANGEMENTS[a.value]);restart_computer();create_arrangement(!0);a.selectedIndex=0});for(var b=$jscomp.makeIterator(_.keys(PREDEFINED_ARRANGEMENTS)),c=b.next();!c.done;c=b.next()){c=c.value;var f=document.createElement("option");f.value=c;f.innerHTML=c.toUpperCase();
a.appendChild(f)}document.getElementById("arr_input").setAttribute("placeholder","Enter one row per line. Row elements are space separated.\n\n"+BLOCKED+" denotes a forbidden block (see examples->FORBIDDEN).\n\n"+SKIP+" denotes a skipped block (see examples->SKIP).\n\n'$pascal ROW' can be used to create Pascal triangles (see examples->PASCAL).\n\n'$invert' as the first line will invert the following arrangement (see examples->INVERT).");var d=document.getElementById("tri_container");computer=new Worker("/pascal_triangle/pascalesque/computer.js");
computer_message_f=function(g){switch(g.data.type){case "pathsComputed":NUMPATHS=g.data.numpaths;TOO_MANY_PATHS||(PATHS_COMPUTING=!1,PATHS_READY=!0,document.getElementById("pathscount").innerHTML=NUMPATHS,_.wrap(function(){add_per_block_counts(g.data.pbc);on_lookup_input_changed()},function m(l){d.children.length==CURRENT_ARRANGEMENT.length?l():setTimeout(m,10,l)})());break;case "nextPath":var e=document.getElementById("colorcycle");draw_path(g.data.prevpath,"",!1);draw_path(g.data.path,"nocycle"===
e.value?"rgba(65, 223, 208, 255)":get_next_color(),"blocks"===e.value);break;case "tooManyPaths":console.log("too many paths: "+g.data.max+" "+g.data.length);TOO_MANY_PATHS||(document.getElementById("pathscount").innerHTML="aborted.. not enough memory",computer.postMessage({type:"destroyPaths"}));TOO_MANY_PATHS=!0;PATHS_READY=!1;break;case "pascalComputed":e=g.data.tri;setTimeout(create_arrangement,0,g.data.docompute,e);_PASCAL_ARRANGEMENT=e;set_arrangement((g.data.doreverse?"$invert\n":"")+("$pascal "+
e.length));var h=document.getElementById("wait_hint");h.innerHTML="get text for pascal "+e.length+"...";h.style.visibility="visible";break;case "test":console.log(g)}};computer.addEventListener("message",computer_message_f);downloader=new Worker("/pascal_triangle/pascalesque/downloader.js");downloader.addEventListener("message",function(g){switch(g.data.type){case "urlCreated":console.log(g.data.url),download_arrangement(g.data.url,g.data.suggested)}})}window.addEventListener("load",main);var Elem=function(a,b,c,f){this.n=a;this.r=b;this.direction=c;this.context=f};
Elem.prototype.compute_paths=function(a){var b=this;if(this.context.PATHS.length>=this.context.MAX_PATHS&&this.context.DO_TRIM)this.halve_paths(),this.compute_paths(a);else if(this.cell_value=this.context.CURRENT_ARRANGEMENT[this.n][this.r],!(this.cell_value===this.context.BLOCKED||0>this.r||this.r>=this.context.CURRENT_ARRANGEMENT[this.n].length)){var c=this.id();this.cell_value===this.context.SKIP?this.context.PER_BLOCK_COUNT[c]=0:_.has(this.context.PER_BLOCK_COUNT,c)?this.context.PER_BLOCK_COUNT[c]+=
1:this.context.PER_BLOCK_COUNT[c]=1;if(this.n==this.context.CURRENT_ARRANGEMENT.length-1)this.cell_value!==this.context.SKIP&&(0==this.context.PATH_COUNT%this.context.EVERYNTHPATH&&this.context.PATH_COUNT<this.context.MAX_PATHS&&this.context.PATHS.push(new Path(a)),this.context.PATH_COUNT++);else{var f={"-1":["left","right"],1:["right","left"]},d=this.context.CURRENT_ARRANGEMENT[this.n].length,g=this.context.CURRENT_ARRANGEMENT[this.n+1].length,e=d===g?0:Math.ceil((Math.abs(d-g)-1)/2);c=1==Math.abs(d-
g)%2;g=d>g?-1:1;d=new Elem(this.n+1,this.r+g*e,c?f[""+g][0]:"up",this.context);f=c&&new Elem(this.n+1,this.r+g*(e+1),f[""+g][1],this.context);this.cell_value===this.context.SKIP&&0<this.n?(c=[d,f].filter(function(h){return h.direction==b.direction})[0])&&c.compute_paths(a.concat(c)):(d.compute_paths(a.concat(d)),c&&f.compute_paths(a.concat(f)))}}};Elem.prototype.simplify=function(){return[this.n,this.r]};Elem.prototype.id=function(){return this.n+";"+this.r};
Elem.prototype.halve_paths=function(){this.context.PATHS=_.pairs(this.context.PATHS).filter(function(a){a=$jscomp.makeIterator(a);var b=a.next().value;a.next();return 0==b%2}).map(function(a){a=$jscomp.makeIterator(a);a.next();return a.next().value})};var Path=function(a){this.path=a};Path.prototype.simplify=function(){return this.path.map(function(a){return a.simplify()})};var _CURRENT_ARRANGEMENT=[],_PATHS=[],MEMSIZE_ELEM=25,PREVIDX=0,CURIDX=0;importScripts("https://cdn.jsdelivr.net/npm/underscore@1.13.1/underscore-umd-min.js");importScripts("/pascal_triangle/pascalesque/path.js");
function compute_paths(a){_PATHS=[];var b={CURRENT_ARRANGEMENT:a.current_arrangement,PATHS:_PATHS,PER_BLOCK_COUNT:{},BLOCKED:a.blocked,SKIP:a.skip,MAX_PATHS:a.memlimit/MEMSIZE_ELEM/a.current_arrangement.length,PATH_COUNT:0,EVERYNTHPATH:a.everynthpath,DO_TRIM:a.dotrim};if(0<a.current_arrangement.length){a=$jscomp.makeIterator(_.range(a.current_arrangement[0].length));for(var c=a.next();!c.done;c=a.next())c=new Elem(0,c.value,"right",b),c.compute_paths([c]);PREVIDX=CURIDX=0;postMessage({type:"pathsComputed",
numpaths:b.PATH_COUNT,pbc:b.PER_BLOCK_COUNT});_PATHS=b.PATHS}}function pascal(a){function b(c){var f=[1].concat(Array(c)),d=Math.floor(c/2),g=BigInt(1);_.range(1,c+1).forEach(function(e){f[e]=e>d?f[c-e]:g=g*BigInt(c-e+1)/BigInt(e)});return f}return _.range(a).map(function(c){return b(c)})}
self.addEventListener("message",function(a){switch(a.data.type){case "computePaths":compute_paths({memlimit:a.data.memlimit,current_arrangement:a.data.current_arrangement,blocked:a.data.blocked,skip:a.data.skip,everynthpath:a.data.everynthpath,dotrim:a.data.dotrim});break;case "getNextPath":0<_PATHS.length&&(postMessage({type:"nextPath",prevpath:_PATHS[PREVIDX].simplify(),path:_PATHS[CURIDX].simplify()}),PREVIDX=CURIDX,CURIDX=(CURIDX+1)%_PATHS.length);break;case "destroyPaths":_PATHS=null;break;case "computePascal":var b=
a.data.doreverse,c=pascal(a.data.row);postMessage({type:"pascalComputed",tri:b?c.reverse():c,docompute:a.data.docompute,doreverse:b})}});var _PREVIOUS_OBJECT_URL="";function save_arrangement(a){a=new Blob([a.map(function(b){return b.join(" ")}).join("\n")+"\n"],{type:"text/plain"});null!==_PREVIOUS_OBJECT_URL&&self.URL.revokeObjectURL(_PREVIOUS_OBJECT_URL);return _PREVIOUS_OBJECT_URL=self.URL.createObjectURL(a)}self.addEventListener("message",function(a){switch(a.data.type){case "createDownloadURL":var b=save_arrangement(a.data.current_arrangement);postMessage({type:"urlCreated",url:b,suggested:a.data.suggested})}});
